name: WireGuard connection
description: Set up WireGuard connection

inputs:
  config:
    description: WireGuard Configuration file
    required: true

runs:
  using: composite
  steps:
    - run: |
        readonly config='${{ inputs.config }}'
        DEBIAN_FRONTEND=noninteractive sudo apt-get update 
        DEBIAN_FRONTEND=noninteractive apt-get -y install wireguard
        echo "$config" > /etc/wireguard/github.conf
        sudo wg-quick up github || exit 1
      shell: bash
branding:
  icon: star
  color: blue
